# DevSpace configuration for postgres-memory service development
version: v2beta1

# Deployment pipelines
pipelines:
  # 'devspace deploy' - Build and deploy production images
  deploy: |-
    build_images --all
    create_deployments --all

  # 'devspace dev' - Deploy production, override with dev images, file sync  
  dev: |-
    create_deployments --all
    start_dev --all

# Image build configuration  
images:
  postgres-memory:
    image: postgres-memory
    dockerfile: ./Dockerfile
    context: ./

# Kubernetes deployments
deployments:
  postgres-memory:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: ${runtime.images.postgres-memory.image}
            tag: ${runtime.images.postgres-memory.tag}
          # Override resources for in-cluster local development
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"

# Development configuration - active during 'devspace dev'
dev:
  postgres-memory:
    imageSelector: postgres-memory
    devImage: golang:1.24-bookworm
    command: ["sh", "-c", "cd /app && go run main.go"]
    namespace: default
    # Stream logs instead of terminal
    logs:
      lastLines: 50
    # File synchronization for hot reload
    sync:
      - path: ./:/app
        startContainer: true
        excludePaths:
          - .git/
          - .devspace/
          - Dockerfile
          - devspace.yaml
          - chart/
          - "*.log"
    # Restart container when Go files change
    restartHelper:
      inject: true
    # Enable SSH for IDE integration
    ssh:
      enabled: true