{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "evaluator-metric.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evaluator-metric.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ark.mckinsey.com
  resources:
  - models
  - queries
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - events
  verbs:
  - get
  - list
{{- end }}